<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx.Http" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentProcessor.Core\DocumentProcessor.Core.csproj" />
    <ProjectReference Include="..\DocumentProcessor.Persistence\DocumentProcessor.Persistence.csproj" />
  </ItemGroup>

</Project>
